#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Custom functions
reload() {
  source ~/.zprofile
  source ~/.zshrc
}

# Aliases
alias ll='ls -lha'
alias tf=terraform
alias tfplan='terraform plan -out tf.plan'
alias tfapply='terraform apply tf.plan'

# >>>> Vagrant command completion (start)
fpath=(/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/contrib/zsh $fpath)
compinit
# <<<<  Vagrant command completion (end)
